/* Cardápio – edite aqui os itens e descrições ("Nome|Descrição") */
const M={
"Entradas":["Hackpeter","Bolinho de Bacalhau (6 unidades)","Camarão Aperitivo Don Brunno|Camarão médio empanados","Carpaccio de Carne|Lâminas de carne temperada com azeite de oliva, limão, alcaparras e parmesão","Torradas com três patês","Cesta de Pães com 3 Patês","Filé mignon na chapa","Frango à passarinho","Calabresa acebolada na chapa","Provolone à milanesa","Tábua de Frios Don Brunno|5 tipos de queijos (minas, mussarela, parmesão, prato e provolone), salame italiano, uvas, azeitonas, ovos de codorna e palmito","Tábua Medieval|3 tipos de queijo (mussarela, prato e provolone), 1 tipo de salame (italiano), azeitonas","Tábua à Itália|Salame italiano, queijo branco e azeitonas","Porção Florença|Queijo provolone","Porção Turim|Queijo parmesão","Porção Bolonha|Salame italiano","Queijo minas com tomate seco","Queijo branco com orégano e azeite de oliva","Polenta Frita","Batata Fritas","Aipim frito com bacon","Torradas","Porção de azeitonas"],
"Massas":["Opção: massa verde · 1 pessoa|Spaguetti, Talharim ou Fettuccini","Ao Sugo","Molho Bolonhesa","Molho Branco","Molho Quatro Queijos","Alho e Óleo","Calabresa Acebolada","Molho Frango","Mignon Acebolado","Molho de Camarão","Molho Italiano|Molho branco com tomate seco e azeitona preta","Molho Funghi","Com Galinha Caipira","À Carbonara|Baycon, gema, molho branco","À Marguerita|Tomate, cebola e manjericão","À Jardineira|Brócolis e cenoura","Al Mare|Peixe, camarão e lula"],
"Risoto":["1 pessoa","Risoto de Camarão","Risoto de 4 Queijos","Risoto ao Funghi","Risoto de Mignon"],
"Nhoque":["Nhoque Don Brunno","Ao Sugo","Molho Bolonhesa","Molho Branco","Molho Quatro Queijos","Alho e Óleo","Calabresa Acebolada","Molho Frango","Mignon Acebolado","Molho de Camarão","Molho Italiano|Molho branco com tomate seco e azeitona preta","Molho Funghi","Com Galinha Caipira","À Carbonara","À Marguerita|Tomate, cebola e manjericão","À Jardineira|Brócolis e cenoura","Molho La Mare|Camarão, lula, peixe"],
"Sopas · Panquecas · Lasanhas":["Sopas e Cremes|Capeletti · Creme de Aspargo · Creme de Palmito · Canja","Panquecas|Frango com Catupiry · Carne","Polenta com Galinha Caipira","Lasanhas|Quatro Queijos · Camarão · Frango · Bolonhesa · Sugo · Bechamel"],
"Saladas":["Salada Verde|Alface americana e crespa, agrião, radite, chicória, rúcula e broto de alfafa","Salada Mista|Folhas verdes, tomate, cenoura, palmito, ovos de codorna e azeitonas","Salada Pesto|Alface americana, crespa e roxa, tomate cereja, palmito, crótons, molho pesto e orégano","Salada Brie|Alface americana, rúcula, presunto parma, queijo brie, queijo minas, crótons, tomate cereja, orégano, molho tártaro e molho de mostarda e mel","Salada de Camarão|Alface americana e roxa, rúcula, camarão, queijo parmesão, gergelim preto e molho tártaro","Salada Páprica|Alface americana, rúcula, queijo minas, crótons, frango, tomate cereja, gergelim preto e molho páprica","Molho Extra|Páprica picante, pesto, mostarda com mel, tártaro, e pepino com limão"],
"Carnes":["1 pessoa","Filé Mignon à moda da casa|Medalhão grelhado acompanhado de salada (palmito, alface, tomate) e spaguetti","Filé Mignon ao Molho Madeira|Medalhão grelhado com molho madeira. Acompanhado de arroz, batata palha e salada (palmito, alface, tomate)","Filé Mignon ao Creme de Aspargos|Medalhão grelhado com creme de aspargo, acompanhado de spaguetti na manteiga e salada (rúcula e tomate)","Filé à Parmegiana|Filé à milanesa gratinado com queijo e molho ao sugo. Acompanhado de arroz e fritas ou spaguetti e fritas","Filé ao Molho de Pimenta Verde|Medalhão grelhado com molho de pimenta verde. Acompanhado de arroz e fritas ou spaguetti e fritas","Filé à Chateaubriand|Medalhão grelhado com molho madeira, aspargo, ervilha, champignon, presunto. Acompanhado de arroz e fritas","Filé Mignon Picante|Medalhão grelhado com pimenta do reino moída, nata com pão. Acompanhado de arroz e fritas ou spaguetti e fritas","Strogonoff de Filé Mignon|Acompanhado de arroz e batata palha ou spaguetti"],
"Frango":["Frango à Moda da Casa|Peito grelhado. Acompanha salada (palmito, alface, tomate) e spaguetti","Frango ao Creme de Tomate Seco|Peito grelhado com creme de tomate seco. Acompanha spaguetti verde","Frango ao Creme de Champignons|Peito grelhado com creme de champignons. Acompanha spaguetti na manteiga","Frango ao Creme de Champignons com Alho Poró|Peito grelhado com creme de champignon e alho poró. Acompanha spaguetti na manteiga"],
"Mar":["Bacalhau à Don Brunno|Bacalhau em posta ao forno com pimentões, cebola e azeitona preta. Acompanha batata dorê","Camarão à Romanesca|Camarão G empanados no queijo parmesão. Acompanha arroz à grega e batata palha","Camarão à New Burger|Camarão M com molho rosê e champignon. Acompanha arroz com açafrão e batata palha","Camarão Gratinado|Camarão M com molho branco e palmito. Acompanha arroz branco e batata palha","Linguado Don Brunno|Crocante filé recheado com palmito e queijo. Acompanha arroz à grega e batata palha","Filé de Linguado|Acompanha legumes no vapor (brócolis e cenoura) e batata cozida","Linguado com Alcaparras|Filé com alcaparras no azeite de oliva. Acompanha batata e legumes na manteiga (brócolis e cenoura)","Linguado New Burger|Filé com molho rosê e champignon. Acompanha arroz à grega e batata palha","Linguado Gratinado|Filé com molho branco e palmito. Acompanha arroz branco e batata palha"],
"Sobremesas":["Petit Gâteau|Sorvete de creme com bolo e cobertura de chocolate","Creme de Mamão Papaia|Sorvete de creme ou morango · Sorvete, mamão papaia e licor de cassis · Sorvete, mamão papaia sem cassis com calda de chocolate","Morango Don Brunno|Morango, suspiro, chantilly, sorvete de creme com cobertura de chocolate","Morango, Suspiro e Chantilly","Morango, Suspiro e Chantilly|Cobertura de chocolate","Sorvete com Cobertura de Chocolate","Sorvete de Creme (2 bolas)","Sorvete de Morango (2 bolas)","Sorvete de Chocolate (2 bolas)","Sorvete de Abacaxi Francês (2 bolas)"]};
